- lib/gettext/po/exceptions.ex
- lib/gettext/po/tokenizer.ex
- test/gettext/po/tokenizer_test.exs
I implemented a first (poor) draft of the tokenizer which only supports tokenizing strings and the `msgid` and `msgstr` keywords. I'm opening a PR this soon so that I know if I'm on the right track.
@josevalim and I discussed tokenizing and parsing on IRC. We were thinking about whether to roll out both a handwritten tokenizer and a handwritten parser or to write a tokenizer and than using with `yecc` (like Elixir).
As far as I looked into `.po` files, the grammar seems very simple. This means that we may be able to use a simple handwritten parser. Let's hear what everybody else has to say :).
> First tokenizer steps

- .gitignore
- lib/gettext/po/parser.ex
- lib/gettext/po/tokenizer.ex
- lib/gettext/po/translation.ex
- src/gettext_po_parser.yrl
- test/gettext/po/parser_test.exs
- test/gettext/po/tokenizer_test.exs
Sorry it took me so long but I've been super busy and I've also been fighting with a nasty bug (read the commit messages if you want to get as angry as I did :smile:).
The syntax errors should be refined a little but the core functionality is there.
Let me know what you think for now!
> .po parser (yecc-based)

- lib/gettext/po/exceptions.ex
- lib/gettext/po/parser.ex
- lib/gettext/po/tokenizer.ex
- test/gettext/po/parser_test.exs
- test/gettext/po/tokenizer_test.exs
I think I could've pushed this right away instead of opening a PR, but a second opinion is always extremely helpful.
I just removed all the `raise` statements from both the parser and the tokenizer, making them return `{:ok, stuff} | {:error, line, reason}` tuples instead. I kind of stole this from EEx.
This way, we can control errors better: for example, when parsing a file instead of a string we can report the line **and the file** where the error occurred instead of the line only. Raising in the tokenizer/parser makes code a little bit harder to control, since every function call could fail badly and that may not always be what we want.
If you're ok with this, I'll merge :). Thanks!
> Errors not exceptions

- lib/gettext.ex
- lib/gettext/interpolation.ex
- lib/gettext/po/tokenizer.ex
- test/fixtures/test_application/priv/gettext/it/LC_MESSAGES/interpolations.po
- test/gettext/interpolation_test.exs
- test/gettext_test.exs
Support for interpolation, yay!
This is by far the "dirtiest" code I had to write within gettext, but I had some trouble finding cleaner ways of doing things. One of the dirtiest things I did is using `Code.eval_quoted/2` ([here](https://github.com/whatyouhide/gettext/blob/interpolation/lib/gettext.ex#L134)), but I couldn't come up with a better way to do this. Another smelly thing is that I shared a variable (`bindings`) between macros, effectively making them *not* hygienic.
I'll wait for any (very welcome!) feedback or suggestions :). Thanks in advance!
> Interpolation

- lib/gettext.ex
- lib/gettext/compiler.ex
- lib/gettext/interpolation.ex
- mix.exs
- test/fixtures/test_application/priv/gettext/it/LC_MESSAGES/default.po
- test/gettext_test.exs
- test/test_helper.exs
I have a working (albeit a bit rough) version of the public API for Gettext, as per #11.
I want to make sure I got everything right:
* `Gettext.d?n?gettext` has to handle responses from the backend like `{:ok, string}`, `{:default, string}` and `{:error, error}`. If I get an `:ok` or a `:default` I return the string, otherwise I raise, right?
* The `d?n?gettext` macros generated in each backend must only handle `{:ok, string}` responses for now, right? I guess `:error`s should be raised and we should warn on `:default` responses, right?
I'm holding off until I'm sure I'm in the right direction; I still don't implement the `Gettext.d?n?gettext` variants which take a locale as an argument, even if that should be super-quick to do.
Comments? :)
> Public API

- lib/gettext/compiler.ex
- lib/gettext/po.ex
- lib/gettext/po/parser.ex
- test/gettext/po/parser_test.exs
- test/gettext/po_test.exs
Hey there @josevalim, I implemented the `%Gettext.PO{}` struct we talked about some time ago, can you take a quick look at this to see if you had something like it in mind?
What I tried to do is separating responsibilities as much as possible: I think `Gettext.PO.Parser` shouldn't know about `%Gettext.PO{}`s, so I made `Gettext.PO.Parser.parse/1` return a tuple like `{:ok, headers, translations}` instead of `{:ok, translations}`. An instance of `%Gettext.PO{}` is built up in `Gettext.PO.parse_(string|file)` so that only `PO` knows about `%PO{}`. Wdyt?
> `%Gettext.PO{}` struct

- lib/gettext/po.ex
- lib/gettext/po/parser.ex
- lib/gettext/po/plural_translation.ex
- lib/gettext/po/translation.ex
- src/gettext_po_parser.yrl
- test/gettext/po/parser_test.exs
- test/gettext/po_test.exs
Opening the PR just to notify you, I'm merging it right away :).
I added the `:po_source` field to both the `Translation` and `PluralTranslation` structs, as discussed with @josevalim on IRC. This field is a `{file, line}` tuple which points to where a translation comes from. For now, the `line` in the tuple will be used by the parser in order to throw meaningful errors when duplicate translations are found; the `file` is still unused, but we may use it later on.
There's actually one thing that bothers me: in order to have a file in the `{file, line}` tuple, we have to loop through all the translations in `Gettext.PO.parse_file/1` because we actually don't have a filename before that step; I don't love this but it's the only *very simple* way I could think of (an alternative would have …
> `:po_source` field for translations

- lib/gettext/po/parser.ex
- test/gettext/po/parser_test.exs
This PR handles duplicate translations. The implementation of the function that checks for duplicates uses `throw`/`catch` in order to traverse the list of translations only one but the code is very simple and straightforward, so that should not be a problem. Thanks @josevalim for the help!
> Duplicate translations

- lib/gettext.ex
- test/gettext_test.exs
This function runs a given function with the process locale set to the given locale. Useful in many situations, tests included.
Closes #28.
> Add Gettext.with_locale/2

- lib/gettext/compiler.ex
- lib/gettext/extractor.ex
- lib/gettext/extractor_agent.ex
- test/gettext/extractor_test.exs
Basically, files were merged correctly only when one of the Gettext macros was used; files that weren't "touched" by one of the macros didn't change at all. This commit refactors things around so that we register every backend in `Gettext.__using__` (only during extraction) in order to know every `.pot` file at merging time.
Once we have every existing `.pot` files and a bunch of extracted translations (in the form of `%Gettext.PO{}` structs), the algorithm is trivial:
- if the extracted struct has a matching existing `.pot file`, merge them
- if an existing `.pot` file has no matching extracted struct, merge it with an empty `%Gettext.PO{}` struct (which means just purge obsolete translations)
- add all the remaining extracted structs as new `.pot` files
@josevalim let me know what you …
> Fix a bunch of bugs with Gettext.Extractor

- lib/gettext/extractor.ex
- lib/mix/tasks/gettext.extract.ex
This PR adds support for the `--merge` option in `gettext.extract`. @josevalim documented the option a couple of commits ago.
The implementation turned out to be pretty straightforward, I'm quite happy with the results.
Closes #38.
> Add support for the --merge opt in gettext.extract

- lib/gettext/fuzzy.ex
- lib/gettext/merger.ex
- lib/gettext/po/translations.ex
- lib/mix/tasks/gettext.extract.ex
- lib/mix/tasks/gettext.merge.ex
- mix.exs
- test/gettext/fuzzy_test.exs
- test/gettext/merger_test.exs
- test/gettext/po/translations_test.exs
- test/mix/tasks/gettext.merge_test.exs
Hey @josevalim, can you have a look at this when you have some time? It's just the foundations of how fuzzy matching would work. It's very simple, but not configurable (I guess we should pass things like `--fuzzy`/`--no-fuzzy` and other options to `gettext.merge`).
Wdyt?
> Fuzzy translations

- lib/mix/tasks/gettext.merge.ex
- mix.exs
@josevalim we store the default for `:fuzzy_threshold` in `:gettext`'s `:env` but we don't load gettext here in a mix task I guess? We don't have the env anyway. FWIW, It also works if I leave the option in the `:env` and call `Application.load(:gettext)` before fetching it, not sure which one is better here (this looks simpler though).
> Move :fuzzy_threshold out of :gettext's env

- lib/gettext/po.ex
- lib/gettext/po/parser.ex
- test/gettext/extractor_test.exs
- test/gettext/po/parser_test.exs
- test/gettext/po_test.exs
@josevalim I'm not proud of the implementation, but the feature works: parsing multiple references on the same line and dumping PO with all the references joined in one line and then wrapped.
On IRC the problem of spaces in file names arrived. I looked at `xgettext` and with this:
```
xgettext "foo bar.c" foo.c
```
you get
```po
msgid "foo"
msgstr "bar"
```
So I pretty much decided to use line numbers to separate filenames. So after a line number, everything up to the next line number is the file name. Let me know what you think!
This would close #46.
/cc @tmjoen
> References

- .travis.yml
Since Elixir 1.1.1 is out, there is no need to fetch the beta version
> chore(travis.yml): use Elixir 1.1.1 release

- CHANGELOG.md
- lib/gettext.ex
The backend parameter was missing in some examples.
> Fix docs for get_locale and put_locale

- lib/gettext.ex
- lib/gettext/compiler.ex
- test/fixtures/test_application/priv/gettext/it/LC_MESSAGES/default.po
- test/gettext_test.exs
Should close #55.
Before this PR, empty msgstrs were treated like any other msgstr. This resulted in a nasty behaviour when generating new PO files (from POT files) with e.g. `mix gettext.merge`, because empty
msgstrs were being returned.
This PR changes the behaviour of the `Gettext.Compiler`, which now doesn't generate a function clause for translations with an empty msgstr at all. This means such translations will fallback to the dynamic clauses of `lgettext` and `lngettext`, which just return the msgid (after interpolation) in a `{:default, _}` tuple. Plural translations are treated this way if they have one or more empty msgstrs.
/cc @chrismccord and @endersstocker
> Fallback to default clauses when msgstrs are empty

- README.md
Just so people don't use the wrong versions in their projects.
> Update README instructions to 0.8

- lib/gettext/compiler.ex
- test/gettext_test.exs
@josevalim makes sense? I just reworded the error message very slightly (e.g., I say "use the functions in the Gettext module" instead of "use the Gettext module").
> Better error message for non compile-time strings

- lib/gettext/compiler.ex
- test/gettext/po_test.exs
- test/gettext_test.exs
Implements the ideas discussed in #75.
> Warning for slashes in domains

- lib/gettext/extractor.ex
- src/gettext_po_parser.yrl
- test/gettext/extractor_test.exs
- test/gettext/po/parser_test.exs
- test/gettext/po_test.exs
We're now:
* adding headers to new POT files (we already added them to new PO files), so that informative comments are kept as the result of being attached to the headers
* handling "dangling" comments, i.e., comments that are not followed by translations (we're simply throwing them away)
> Better comment handling

- lib/gettext.ex
- lib/gettext/plural.ex
- test/gettext/plural_test.exs
@josevalim I kept `pt_BR` to be compliant with [this](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals) and [this](http://localization-guide.readthedocs.org/en/latest/l10n/pluralforms.html), and because the implementation isn't really any more complicated IMO. I can remove it and treat `pt_BR` as `pt` if you prefer. Wdyt?
> Plural enhancements

- lib/gettext.ex
- lib/gettext/compiler.ex
- lib/gettext/plural.ex
- test/gettext_test.exs
We were reading the `:plural_forms` option (that specifies which pluralizer module to use) from the configuration of the `:gettext` application, but we want to read that from the configuration of each backend (the one passed to `use Gettext`).
I fixed that and also polished the modules for `Gettext.Plural`.
> Better plural forms

- lib/gettext.ex
- lib/gettext/backend.ex
- lib/gettext/compiler.ex
This behaviour is implemented by all modules that call `use Gettext`. It's mostly useful for documentation. I haven't included the `lgettext/4` and `lngettext/6` callbacks in the behaviour as we keep those function "hidden" (not documented anywhere currently); however, we call those from the `Gettext.*gettext` functions so it may be worth to add them to the behaviour, so that if people want to implement weird Gettext backends they have *all* the correct callbacks.
Wdyt @lexmag and @josevalim?
> Add the Gettext.Backend behaviour

- lib/gettext/po/parser.ex
- test/gettext/po/parser_test.exs
yecc prints tokens as Erlang terms (e.g., binaries are `<<"like this">>`) instead of Elixir terms. This commit introduces a pretty ugly hack that parses and rewrites yecc error reasons to print some terms as Elixir terms (like binaries) instead of Erlang terms.
This is ugly, but it's necessary given the lack of extensibility in yecc; in fact, Elixir itself does this as can be seen here: https://github.com/elixir-lang/elixir/blob/b806511b887776c1f9ab349a377350b8c9c069f1/lib/elixir/src/elixir_errors.erl#L51-L103.
This should contribute to solving the issues described in #89.
> Don't print tokens as Erlang terms in syntax error

- lib/gettext/interpolation.ex
- test/gettext/interpolation_test.exs
This fixes a bug where it is not possible to specify the same interpolation key twice in a string
e.g. `"Hello %{name}. Goodbye %{name}"`
> Allow duplicate interpolation keys

- lib/gettext.ex
- lib/mix/tasks/compile.gettext.ex
- test/mix/tasks/compile.gettext_test.exs
This should fix #99.
Right now, the `:gettext` compiler uses a hardcoded default wildcard of `"**/*.po"` to find all the PO files under `priv` (so that manifests can be built and updated). This turns out to be very slow when there are a lot of files in `priv`, as it may happen for example in a Phoenix application with a lot of stuff in `priv/vendor` (see https://github.com/phoenixframework/phoenix/issues/1671).
This commit adds support for the `:compiler_po_wildcard` option to the `:gettext` application. This option specifies the wildcard that the compiler uses  to find PO files (relative to `priv`). It defaults to `gettext/*/LC_MESSAGES/*.po`, which is in line with the default directory for Gettext backends, which is `priv/gettext`.
I'm not 100% sure about the name of this option, but I …
> Add a :compiler_po_wildcard option to the Gettext configruation

- lib/gettext.ex
- lib/gettext/compiler.ex
The two will be merged, giving precedence to the configuration passed to `use Gettext`.
\cc @josevalim, this looks pretty good to me, but I would love another pair of eyes on docs especially :)
> Read the config both from "use Gettext" and Mix.Config

- lib/gettext.ex
- lib/gettext/compiler.ex
- lib/gettext/interpolation.ex
\cc @josevalim, this should be enough to handle all the `bindings` types :) Wdyt?
> Handle non-map bindings in the l(n)gettext functions

- lib/gettext.ex
- lib/gettext/compiler.ex
- test/gettext_test.exs
`l*gettext` functions generated in backends will now assume bindings are a map and the only conversion from keyword list to map will be performed in `Gettext.*gettext` functions. These functions are used by the `*gettext` macros generated in each backend as well, so each case will be covered.
@josevalim wdyt of this? We were using `bindings \\ %{}` in `l*gettext` functions but those are never called directly (except in tests), so I think being stricter makes sense there. Also typespecs should be a bit clearer this way (related to #115 which I'm trying to fix).
> Only check for the type of bindings in Gettext.*gettext functions

- lib/gettext.ex
- lib/gettext/compiler.ex
@josevalim I remember we decided to keep the call to `Gettext.Compiler.signatures/0` in `Gettext.__using__/1` but now I don't really see the point 😕 It makes it a bit harder to follow the whole flow since that call is far from the rest of related calls to `Gettext.Compiler.dynamic_clauses/0` and friends. Wdyt?
> Move some function generation from Gettext to Gettext.Compiler

- lib/gettext/compiler.ex
- test/gettext_test.exs
Instead of `IO.puts(:stderr, msg)`.
Closes #128.
> Use Logger.error/1 for runtime warnings

- lib/gettext.ex
- lib/gettext/backend.ex
- lib/gettext/compiler.ex
- test/gettext_test.exs
Would close #131.
\cc @manukall
@josevalim I went with this approach in `*ngettext_noop` where `{msgid, msgid_plural}` is returned because that is what is often used to represent a plural translation (in Ecto for example, I think right?) and because the Wordpress implementation of these functions (one of the few I found) does the same (returns every info you pass to it basically). The Python implementation seems to ask for `n` as well and does the English pluralization rule, but of the two I think I prefer the tuple one. Wdyt?
> Define *gettext_noop macros that mark translations for extraction

- lib/gettext/po/tokenizer.ex
- src/gettext_po_parser.yrl
- test/gettext/po/parser_test.exs
- test/gettext/po/tokenizer_test.exs
This is a first shot at #142, where I implement support for parsing translations with `msgctxt`, but completely ignoring such context when parsed:
```pot
msgctxt "my context"
msgid "foo"
msgstr "bar"
```
I think as a first step it's good to have this. It ensures we are able to parse files from different editors and such, and this is good. At the same time, we don't change the output currently dumped by Gettext; after all, the use case in #142 is to not fail on files that have `msgctxt`, but not use Gettext to generate such files. I'd love some opinions! :)
Btw, we could start supporting msgctxt but me and @josevalim discussed this a long time ago and decided it was not worth it. It would bring a lot of changes, so it's something that if we consider, we should think about a lot.
(Closes …
> Parse msgctxt when present but ignore it

- .travis.yml
I also updated the .travis.yml to match elixir-lang/ex_doc#656 so that only the newest and oldest Elixir/OTP pairs are tested.
> Test on Elixir 1.4.0

- lib/gettext.ex
- test/gettext_test.exs
This commit introduces the idea of a "global" Gettext locale that spans across all backends. I introduced `Gettext.put_locale/1`, `Gettext.get_locale/0`, and `Gettext.with_locale/2` to interact with it. Now, the algorithm to get a locale when calling Gettext functions for a given backend is roughly this:
pdict_for_backend || pdict_global || default_for_backend || default_global
A few notable things:
* I removed the optimization in `Gettext.get_locale/1` that stored the default locale in the pdict in case there was no pdict; this conflicted with the algorithm above. Now, every call to `get_locale/1` with no previous call to `put_locale/1,2` will result in one or two ETS fetches (from the app configs).
* I changed the behaviour of `with_locale/2,3` slightly to adjust to the change above: …
> Introduce a global locale (per-process) for all Gettext backends

- lib/gettext/compiler.ex
- test/fixtures/test_application/bad_translations/ru/LC_MESSAGES/errors.po
- test/gettext_test.exs
If a translation for a given locale now is missing one or more plural forms for that locale, we will warn when compiling the Gettext backend and raise at runtime if the user tries to use the missing plural form.
> Warn when compiling and raise at runtime for missing plural forms

- lib/gettext/po.ex
- lib/gettext/po/parser.ex
- test/gettext/po/parser_test.exs
- test/gettext/po_test.exs
GNU `msgmerge` separates flags by `", "`, do this on output as well,
but accept `[, ]+` as a separator on input.
When parsing multiple flags of a file generated by `msgmerge`, the separating `","` is currently parsed as being part of the preceding flag, which is obviously not what was intended by `msgmerge`.
> flags can be separated by [, ]+

- lib/gettext.ex
- lib/gettext/compiler.ex
- test/gettext_test.exs
This speeds up compilation time about roughly 20% in large gettext backends.
On the sample project we had, the original time compilation time of the backend was 30s, which falls down to 24s with the first commit.
By using the option in the second commit, compilation time drops to 11s (my machine has 2 cores, the more than 2x increase is probably thanks to the smaller beam files).
> Define intermediate functions per locale + domain and support parallel compilation

- lib/gettext.ex
%{} is the type for an empty map, we should use map() instead.
> Fix bindings type.

- lib/gettext.ex
- lib/gettext/backend.ex
- lib/gettext/compiler.ex
- test/gettext_test.exs
I went with two callbacks, `handle_missing_translation/4` for translations and `handle_missing_translation/6` for plural translations. I don't think that the approach with the exception, similar to `handle_missing_bindings/2`, worked very well in this case. We don't warn or don't produce an error message by default when a translation is missing, so the exception would feel a bit forced.
@josevalim a point one could make is that a user might want to actually raise on every missing translation, and in that case having a single exception (in a single callback, not two) that they can just raise might be beneficial. If you still think that's the better approach, it'll be an easy change to this PR :).
> Add handle_missing_translation/4,6 callbacks to Gettext backends

- lib/gettext/po/translations.ex
- test/gettext/po/parser_test.exs
Often you need to control your translations so adding msgctxt allows you
to have different translations even if you are using the same msgid.
Here we are making sure that this doesn't trip the duplication check.
This is hopefully the last bit for this feature request at least on the parsing side:
https://github.com/elixir-lang/gettext/issues/199
> Allow for duplicates with msgctxt

- lib/gettext/po.ex
- test/gettext/po_test.exs
Closes #212.
If the first reference was longer than the whole line length, we
would write an empty "#:" reference comment because of the way that
dumping of reference comments was built. I changed the implementation
so that we chunk references so that each chunk represents a line to
dump, which fixes the problem described above.
> Fix a bug when dumping references

- lib/gettext/compiler.ex
Closes #206.
This PR implements what was suggested by @josevalim in #206. Basically, when we compile a plural translation, if the only interpolation key in the msgstrs is `%{count}` then we know it's gonna be in the bindings because **we** put it there. For this reason, we don't need to have a fallback to dynamically interpolate bindings in those cases and in fact removing the fallback clause fixes a Dialyzer error.
This solution works but we should note that `generated: true` as also suggested by @josevalim in #206 also fixes the Dialyzer warning and keeps the code simpler, but at the cost of potentially hiding other errors/warnings. Wdyt @josevalim, which solution should we go with?
> Improve generation of interpolated clauses

- README.md
The previous version of formatting causes difficulties when trying to copy a line with a double click.
After inserting into the code, you have to delete parentheses.
In my opinion, this formatting option is more convenient and adapted for copy paste.
> Human copyable format

- lib/gettext/po/parser.ex
This resolves all Dialyzer warnings for the `Gettext.PO` module.
Issue elixir-gettext/gettext#205
Issue kenny-evitt/gettext#1
> Fix spec and update doc for one function

- lib/gettext.ex
Thanks from the library. While reading docs I've noticed there is in-proper `with` inside the sentence.
> Fix typo in default locale docs

- CHANGELOG.md
- lib/gettext.ex
- lib/gettext/compiler.ex
- test/fixtures/test_application/translations/es/LC_MESSAGES/default.po
- test/gettext_test.exs
Added a configuration option `allowed_locales` to restrict the locales that gettext bundles in the backend.
This patch introduces slightly more changes than I was expecting. 
In the previous version, the filesystem was read twice. One to discover the locales, and another to load the po files.
If I had kept this approach, I should have done the filtering of locales twice, with different inputs.
In the current approach, I reach for the filesystem once, and filter the PO files there based on the configuration, returning the path, locale and domain in the same data structure.
This structure is then cascaded to the different compilers
closes #238
> Support configuration of locales by environment

- test/mix/tasks/compile.gettext_test.exs
There is a chance that the previous assertion leaves the timestamps in
the following state:
| File                              | Timestamp
------------------------------------|------------------------------
| Manifest .compile_tmp_gettext_bar | {{2020, 1, 21}, {17, 49, 57}}
| Manifest .compile_tmp_gettext_foo | {{2020, 1, 21}, {17, 49, 57}}
| PO foo/en/LC_MESSAGES/hello.po    | {{2020, 1, 21}, {17, 49, 56}}
which means that when touching `hello.po` to have a newer timestamp, ends
up with the same timestamp as the manifest. This marks the whole manifest as "not stale".
With this patch, i'm forcing the touch of the file to be later than the
oldest of the timestamps of the PO or the manifest.
This should fix the error https://travis-ci.org/elixir-gettext/gettext/jobs/638875306?utm_medium=not …
> Ensure that touching the PO file happens after the manifest

- lib/gettext.ex
- lib/gettext/extractor.ex
- test/gettext/extractor_test.exs
I have been working on one Phoenix app with a few people for 1 year now. Every time we happened to add strings to the same Gettext domain on two different feature branches, we would get merge conflicts because the standard behavior of Gettext is to append strings to the end of the file. This is a minor inconvenience for a single file, but a bit annoying if you have more than 5 languages.
We came to the conclusion that we might decrease how often conflicts happen if we changed the default behavior - instead of appending strings at the end, which guarantees conflicts every time, we want to sort them alphabetically by `msgid`.
We used that approach for a few months now, and it does work for decreasing the number of merge conflicts. Thus I want to suggest it as a option for everyone :).
The …
> Allow sorting strings by msgid

- lib/gettext.ex
- lib/gettext/backend.ex
- lib/gettext/compiler.ex
- test/gettext_test.exs
Resolves #253
A given backend can be configured to have a default domain with the option
`:default_domain`, as in:
```elixir
config :gettext, MyApp.Gettext, default_domain: "messages"
defmodule MyApp.Gettext do
use Gettext, otp_app: :my_app, default_domain: "messages"
end
```
When applied, this means that instead of `MyApp.Gettext.gettext("foo")` being
equivalent to `MyApp.Gettext.dgettext("default", "foo")`, it is now equivalent
to `MyApp.Gettext.gettext("messages", "foo")`.
> Configurable Default Domain

- lib/gettext/compiler.ex
Instead of loading everything into memory at once, I'm compiling the locales one by one in a stream, and then passing it to the parallel compiler.
In a project of mine, compile time goes from 2m 11s to 1m25s.
Memory consumption also goes down, from 3.35G to 2.56G
I'm aware the resulting code is not the most elegant. If you have ideas of better takes to do the same, I'm happy to try them. This is the minimal version that accomplishes the task of reducing memory and run time. Other takes would require more involved changes
> Improve parallelism when compiling modules

- lib/gettext/extractor.ex
This is a nitpick, but I noticed that generated pot files have a typo in the comment added on top of them.
> Fix a typo in generated POT file's comment

- lib/gettext/backend.ex
- lib/gettext/plural.ex
- test/gettext/plural_test.exs
"country" refers to a political entity which can cause conflict when territories are disputed.
A list of disputed territories is available at https://en.wikipedia.org/wiki/List_of_territorial_disputes
This commit uses the term "territory" rather than "country" to reflect that locales serve a purpose
to reflect user preferences, not to express a political agreements.
* Annex A to ISO/IEC 15897:1998(E) also refers to "territory" for submissions.
* ISO3166 which lists "country codes" says for "TW" (Taiwan) that ISO recognises Taiwan as "Taiwan, Province of China". This view is not widely accepted by the people who live in Taiwan showing how challenging it is to reflect
both cultural preferences and manage political realities.
Using the term "territory" tends to nullify these issues and focus …
> Change references from "country" to "territory"

- lib/gettext/plural.ex
Hi!
Hope you're well.
It appears that `https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals` is no longer a valid link. This PR suggests using a UDN backup of the `Localization and Plurals` article.
👋
> Use UDN backup for Localization and Plurals.

- lib/gettext.ex
- test/fixtures/test_application/priv/gettext/it/LC_MESSAGES/interpolations.po
- test/gettext_test.exs
According to [the examples](https://hexdocs.pm/gettext/Gettext.html#dngettext/6-examples) `dngettext/6`'s last argument `bindings` is supposed to be optional.
Please let me know If I need to leave the function as is and edit the examples instead.
> Make dngettext/6 bindings optional

- lib/mix/tasks/gettext.merge.ex
Increasing the task timeout, necessary when project starts to get big !
> Increase Mix.Tasks.Gettext.Merge task timeout.

- lib/gettext/compiler.ex
Suppresses warning:
```
warning: variable "bindings" is unused (if the variable is not meant to be used, prefix it with an underscore)
lib/hygeia_gettext.ex:1: HygeiaGettext.T_fr_default.fr_default_lngettext/5
```
This warning happens, because `clauses` can be an empty list. Therefore the variable is actually never used.
> Supress Warning "variable "bindings" is unused"

- lib/mix/tasks/gettext.extract.ex
This was the failure:
```
1) test extracting and extracting with --merge (Mix.Tasks.Gettext.ExtractTest)
test/mix/tasks/gettext.extract_test.exs:19
Assertion with == failed
code:  assert read_file("priv/gettext/it/LC_MESSAGES/my_domain.po") == "#, elixir-format, ex-autogen\n#: lib/other.ex:3\nmsgid \"other\"\nmsgstr \"\"\n"
left:  ""
right: "#, elixir-format, ex-autogen\n#: lib/other.ex:3\nmsgid \"other\"\nmsgstr \"\"\n"
stacktrace:
test/mix/tasks/gettext.extract_test.exs:62: (test)
```
It was caused by the second file written in the test not being recompiled.
cc @josevalim do you know why changing the manifests in `gettext.extract` was not enough, and I had to use `--force`? Did something change in Elixir itself?
> Fix failing test

- lib/gettext/compiler.ex
This fixes a simple spelling mistake.
> Fix typo: `deprecatead` to `deprecated`

- lib/gettext.ex
Gettext.put_locale/{1,2} delegates to Process.put/2
which returns the previously set value for the key which
may be nil or term().
The @spec for Gettext.put_locale/{1,2}
is updated to specify the return of `locale | nil`
to reflect this.
> Fix @spec for Gettext.put_locale/{1, 2}

- lib/gettext.ex
- lib/gettext/backend.ex
- lib/gettext/compiler.ex
- test/gettext_test.exs
To resolve msgctxt not being passed into the fallback function,
we added new callbacks handle_missing_translation/5 and
handle_missing_plural_translation/7 that will get msgctxt.
The default implementations for these two functions call the
old versions respectively, so users implementing the old callbacks
still get the same result.
BUG: https://github.com/elixir-gettext/gettext/issues/303
> Pass msgctxt into handling missing translation functions

- lib/gettext/extractor_agent.ex
- test/gettext/extractor_test.exs
Solves https://github.com/elixir-gettext/gettext/issues/308
Distinct comments for a same Gettext text on extraction, so a `gettext_comment/1` can be added into multiple places inside one or more apps, without duplications at the final `.pot` file.
> Uniq comments for same translation

- lib/gettext/po.ex
- test/gettext/extractor_test.exs
- test/mix/tasks/gettext.extract_test.exs
This PR changes the order in which flags and references are dumped into PO files, so that flags are placed after references. This behavior seems to be common among a small sample of non-Elixir PO files I saw.
In of the projects, I'm going to use transifex.com to enable easier management of translations. However, I've noticed that they output comments in PO files in a different order than Elixir's gettext. They first output file references and then flags, while Elixir's gettext does it the other way. This results in some unnecessary churn in git history, because these 2 lines are swapped back and forth. Folks at transifex.com insist that Elixir's gettext is outputing comments in the wrong order:
> After investigation, our team concluded that the resulting order of the comments is not …
> Dump flags after references in PO files

- README.md
to avoid double wrapping to code block
> Remove redundant indentation in README.md

- lib/gettext.ex
- lib/gettext/extractor.ex
- lib/gettext/merger.ex
- lib/mix/tasks/gettext.merge.ex
- test/gettext/merger_test.exs
Background:
Since even the smallest changes in files can cause a cascade of changed line numbers in po/pot files we're often seeing larger amounts of changes in commits causing the need to re-extract than needed.
By adding the `write_reference_line_numbers` option developers has a way to decide for themselves whether they want to include them or not.
Fixes #321
> Add `write_reference_line_numbers` option

- lib/gettext.ex
- lib/gettext/merger.ex
- lib/mix/tasks/gettext.merge.ex
- test/gettext/merger_test.exs
- test/mix/tasks/gettext.merge_test.exs
Should this be the default behavior or hidden behind a flag?
> Save previous message for fuzzy matches

- lib/gettext.ex
- lib/gettext/extractor.ex
- test/gettext/extractor_test.exs
> Add `sort_by_msgid_case_insensitive`

- lib/gettext/extractor.ex
- test/gettext/extractor_test.exs
Simplifies the code paths quite a bit and is cleaner since the comments are handled via the `Expo.Messages` structs as well.
I had to remove one assertion from a merge test since the comment is introduced in a different place. It is still covered properly in various places though like https://github.com/elixir-gettext/gettext/blob/03f9ba7d51da5b45790f0d60c73e73d50664e6b6/test/gettext/extractor_test.exs#L51
> Simplify writing of initial pot file top comments

- lib/gettext/extractor.ex
- lib/mix/tasks/gettext.extract.ex
- test/mix/tasks/gettext.extract_test.exs
I can't come up with a small test-case. Without it the check fails in one of my applications because `contents` is `iodata` and not a string.
Fixes #334
> Fix up-to-date check in extractor

- .github/dependabot.yml
- .github/workflows/main.yml
Gets rid of 
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```
> Update actions/checkout & setup Dependabot for actions

- lib/gettext/merger.ex
- test/gettext/merger_test.exs
> Fix duplicated filename in reference when using write_reference_line_numbers

- lib/gettext/compiler.ex
- lib/gettext/merger.ex
- lib/gettext/plural.ex
- lib/mix/tasks/gettext.merge.ex
- test/fixtures/single_messages/it/LC_MESSAGES/default.po
- test/gettext_test.exs
- test/mix/tasks/gettext.merge_test.exs
- test/test_helper.exs
Closes #318
This makes it possible to react precisely to the header instead of using predefined formats.
> Supply plurals forms header to Gettext.Plural callbacks

- lib/gettext/plural.ex
Oops, that should not have been merged in #343 
Copied from https://github.com/elixir-lang/elixir/blob/df056c2cda6c046839d42c830888c79c18287bfd/lib/elixir/lib/code.ex#L1648
> Set correct error message for ensure_loaded! in Plural

- lib/gettext/extractor.ex
I have in the same app 2 gettext backends, each one having its own domain.
I want both backend translation files to live in the same usual `priv/gettext` folder: the different domain name ensures they will not overwrite each other.
When extracting translations the `warn_on_conflicting_backends/1` function issues a warning about that case but then it also crashes:
```shell
warning: the Gettext backend Blog.Gettext has the same :priv directory as Marketplace.Gettext, which means they will override each other. Please set the :priv option to different directories or use Gettext inside each backend
(elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
(gettext 0.22.0) lib/gettext/extractor.ex:103: Gettext.Extractor.pot_files/2
(gettext 0.22.0) …
```
> Fix extractor crash in case of conflicting backends

- lib/gettext/plural.ex
- test/mix/tasks/gettext.merge_test.exs
I found that we generate the outdated `nplurals=X` only headers by default when using `gettext.merge` for a new locale. That will directly result in a deprecation warning.
> Implement `Plural.plural_forms_header/1` for default implementation

- lib/gettext/extractor.ex
- test/gettext/extractor_test.exs
```elixir
1) test merge_template/2 allowed messages are kept (Gettext.ExtractorTest)
test/gettext/extractor_test.exs:90
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Gettext.Extractor.protected?/2
The following arguments were given to anonymous fn/1 in Gettext.Extractor.protected?/2:
[{"foo.ex", 1}, {"bar.ex", 1}]
code: assert Extractor.merge_template(old, new, excluded_refs_from_purging: ~r{^web/static/}) ==
stacktrace:
(gettext 0.23.0-dev) lib/gettext/extractor.ex:425: anonymous fn/1 in Gettext.Extractor.protected?/2
(elixir 1.14.1) lib/enum.ex:4136: Enum.any_list/2
(gettext 0.23.0-dev) lib/gettext/extractor.ex:295: anonymous fn/3 in Gettext.Extractor.merge_template/3
(elixir 1.14.1) lib/enum.ex:4249: Enum.flat_map_list/2
(gettext 0.23.0-dev) …
```
> fix: Gettext.Extractor references no function clause matching

- lib/gettext/plural.ex
Fixes https://github.com/elixir-gettext/gettext/issues/358
We can't use ensure_compiled!/1 for versions under 1.12+
> Change from ensure_loaded/1 to ensure_compiled/1

- lib/gettext.ex
This PR improves two things:
1. Rename "translation IDs" to "message IDs", because:
+ in GNU Gettext, we use msgid.
+ in other docs of this repo, we use "message IDs".
+ so, "translation IDs" is not good, and will cause confusion with the "message IDs", although they both refer to the same thing.
2. Move "Default Domain" to a better place, because:
+ it's good to group related contents like section "Locale" did.
> Improve docs

- lib/mix/tasks/gettext.merge.ex
`:nofile` error of #358 has been solved for a while, but I found it's not solved completely. 
I can still see the `:nofile` error when working with **Gettext with custom plural module**. I created a repo for reproducing the problem:
+ repo: https://github.com/plastic-gun/elixir-gettext-nofile
+ every commit in this repo is self-descriptive, you can track them to reproduce the problem.
+ `README.md` contains the following contents:
- how to reproduce?
- what is wrong?
- the problem 
- the reason
- the solution
---
I found the solution is very easy - use `mix loadpaths`, such as:
```sh 
$ mix do loadpaths + gettext.merge priv/gettext --locale en_US
```
But, to minimize surprises, I believe it would be better to make the changes within `Mix.Tasks.Gettext.Merge`, which helps to reduce the …
> Ensure all modules are properly loaded for "mix gettext.merge"

- lib/mix/tasks/gettext.extract.ex
- mix.lock
Don't rely on the the last-update timestamp of the manifest to trigger a forced compilation with the Elixir compiler.
The Mix task needs to be re-run, to ensure that previous compilations don't turn this in a noop. This assumes the `compiler.elixir` is sufficient for extracting messages.
Closes #367.
Needs thorough review though, I'm not sure of all the consequences.
> Don't rely on the the last-update timestamp of the manifest for extract mix task

- lib/gettext/plural.ex
An unused private macro emits a warning on Elixir 1.16. Since `ends_in/2` is unused, this PR deletes it. All tests pass.
> Remove unused private macro ends_in/2

- CHANGELOG.md
- mix.exs
I though it makes sense to highlight the way to fix a `Expo.PO.DuplicateMessagesError` directly in the changelog.
I would classify this is a patch release since we handled the messages differently from GNU gettext. Do you agree @whatyouhide or should this be `v0.24.0`?
> Release `v0.24.0`

- .github/workflows/main.yml
Should prevent https://github.com/elixir-gettext/gettext/pull/382#issuecomment-1838814568
> Prevent Unlocked / Outdated Mix Dependencies in CI

- lib/gettext.ex
- lib/gettext/backend.ex
- test/gettext/backend_test.exs
This starts to address #330 by allowing `use Gettext.Backend` in place of `use Gettext`. Small steps, and this should be easy to review 🙃 
I left all the test modules to `use Gettext` because we'll change that later on anyway.
> Introduce "use Gettext.Backend"

- lib/gettext.ex
- lib/gettext/backend.ex
- lib/gettext/compiler.ex
- lib/gettext/extractor.ex
- lib/gettext/macros.ex
- mix.exs
- test/gettext/new_backend_setup_test.exs
- test/mix/tasks/gettext.extract_test.exs
- test/support/mix_project_helpers.ex
First pass, let's see if this is a direction we like.
> Avoid compile-time dependency to Gettext backend

- lib/gettext.ex
- lib/gettext/compiler.ex
- lib/gettext/macros.ex
- mix.exs
- test/gettext/macros_test.exs
Talked about this with @josevalim this morning.
> Refactor Gettext.Macros to generate less code

- CHANGELOG.md
Zach built a nice igniter mix migration task. I thought it would be good to mention it in the changelog to make the update simpler for our users.
> Mention `igniter` in v0.26 Changelog Migration Guide

- lib/gettext/extractor_agent.ex
- test/gettext/extractor_test.exs
> Warn user if conflicting plural messages are defined

- README.md
- lib/gettext.ex
- test/gettext_test.exs
Updated deprecation message to include more details.
> Deprecation message

- lib/gettext/macros.ex
- test/gettext/macros_test.exs
Add support for concatenation with sigils (e.g. `"Hello " <> ~s(world)`).
Fixes #411
> Fix concatenation of sigils

- lib/mix/tasks/gettext.extract.ex
Set a timeout of :infinity when running extract. This is in line with the setting for the merge operation.
Fixes #416
> Don't time out when running the extract task
