lib/gettext.ex
lib/gettext/plural.ex

Working on the first big batch of documentation, wow! I'm opening a PR now so that you can take a look and give feedback if you have time :). I'm sure I'm forgetting something.

[WIP] Docs!

---

lib/gettext/po/plural_translation.ex
lib/gettext/po/tokenizer.ex
lib/gettext/po/translation.ex
src/gettext_po_parser.yrl
test/gettext/po/parser_test.exs
test/gettext/po/tokenizer_test.exs

Hey there, I quickly added support for tokenizing and parsing comments as per #16. I'm opening the PR so that you're all notified but I'm merging it right away since the code is very simple. If you have any comments or feedback I still would appreciate it a lot, and we can change the code later if necessary :). Thanks!

Comments support

---

lib/gettext/compiler.ex
lib/gettext/extractor.ex
lib/gettext/extractor_agent.ex
lib/gettext/po/translations.ex
lib/mix/tasks/gettext.extract.ex
test/gettext/extractor_test.exs
test/gettext/po/translations_test.exs

@josevalim this should be a pretty complete implementation of translation extraction. I left a few comments throughout the commits to discuss a couple of things :)
(docs for the `mix gettext.extract` task are still missing)

Extracting translations

---

lib/mix/tasks/gettext.extract.ex
lib/mix/tasks/gettext.merge.ex

As per #43. This PR just makes the `gettext.extract` and `gettext.merge` tasks more parallel using `Task.async/1` and `Task.await/1`. Should be nice and easy.

Parallelizing tasks

---

lib/gettext.ex
lib/gettext/compiler.ex
test/gettext_test.exs

Implementation of what was discussed in #48. Wdyt? /cc @lexmag @josevalim

Per-backend locale

---

README.md

So that people always use the latest version.

Bump version in README to 0.7

---

lib/gettext/fuzzy.ex

based on the discussion https://github.com/elixir-lang/elixir/pull/3112#discussion-diff-42950249

correct return value for jaro_distance spec

---

lib/gettext.ex
test/gettext_test.exs

Add Gettext.known_locales/1

---

lib/gettext/po.ex
lib/gettext/po/tokenizer.ex
test/fixtures/bom.po
test/gettext/po/tokenizer_test.exs
test/gettext/po_test.exs

Pretty filthy stuff but I'm happy with the result so far!
(thanks to @cloud8421 which reported the BOM bug :+1:)

BOM and invalid bytes

---

README.md

I'm at the Montevideo Elixir meetup, and we have some ideas for
improving the documentation. The idea here is to make the example
less abstract, and clarify the meaning of "3" by providing a
map with some context.

Make example more illustrative

---

lib/gettext.ex

I added one more function call to show that locale switched back

improve with_locale doc example

---

lib/gettext.ex

@josevalim what do you think of this to solve #70?
/cc @lexmag which always has good advices :)

Fail more gracefully in Gettext.*gettext functions

---

lib/gettext/plural.ex
test/gettext/plural_test.exs

Implements what was discussed in #87. @josevalim let me know what you think, but it should be straightforward :)
/cc @maufl

Handle unknown locales in Gettext.Plural

---

lib/gettext.ex
lib/gettext/compiler.ex
test/gettext_test.exs

Raise when the domain is not a binary at compile-time

---

lib/mix/tasks/gettext.merge.ex

\cc @josevalim, point 1. of what we discussed a while back :)

Don't dig into the directory given to gettext.merge

---

lib/mix/tasks/gettext.extract.ex

This will fix #104.
\cc @josevalim

Reenable the "compile" task in the gettext.extract Mix task

---

lib/gettext/interpolation.ex
lib/gettext/merger.ex
lib/gettext/po/parser.ex
test/gettext_test.exs

Noticed these warnings while creating a project using latest phoenix.

Remove 1.4 warnings

---

lib/gettext/compiler.ex

We basically pointlessly used `Enum.reduce/3` instead of good old `Enum.flat_map/2` :) The only thing that changes now is the order of the generated clauses, but that's ok since they're all different clauses.

Refactor some function generation in Gettext.Compiler

---

test/mix/tasks/compile.gettext_test.exs

Pop test project on test exit.

---

lib/gettext.ex
lib/gettext/backend.ex
lib/gettext/compiler.ex
lib/gettext/interpolation.ex
mix.exs
test/gettext/interpolation_test.exs
test/gettext_test.exs

Incorporates #113, closes #107.

Add missing bindings handler

---

lib/gettext/compiler.ex
lib/gettext/interpolation.ex

This version doesn't take a "tag" that it returns as `{tag, interpolated_string}` when interpolation is successful. Instead, it returns either `{:ok, interpolated_string}` or `{:missing_bindings, incomplete_string, bindings}` if bindings are missing.
This simplifies `interpolate/2` both in its implementation as well as its interface, that is, it now either succeeds or fails, the responsibility of handling each of those cases is the caller's.
Would love your thoughts @josevalim :)

Simplify Gettext.Interpolation.interpolate/2

---

lib/gettext.ex

check https://hexdocs.pm/elixir/Application.html#put_env/4

fix `put_env` arity

---

lib/gettext/compiler.ex
lib/gettext/extractor.ex
lib/gettext/po.ex

This is a collection of various typo and documentation fixes.
All hopefully non-controversial.

typos and docs

---

lib/gettext/backend.ex
lib/gettext/compiler.ex
lib/gettext/extractor.ex
lib/gettext/extractor_agent.ex
lib/gettext/merger.ex
lib/gettext/po.ex
lib/gettext/po/parser.ex
lib/gettext/po/plural_translation.ex
lib/gettext/po/translation.ex
test/gettext/extractor_test.exs
test/gettext/merger_test.exs
test/gettext/po/parser_test.exs
test/gettext/po_test.exs

Based on the great work by @roques in #156. 💟

Add support for extracted comments via gettext_comment/1

---

lib/gettext/po.ex
lib/gettext/po/parser.ex
test/gettext/po/parser_test.exs

Support filenames with colons in reference comments

---

lib/gettext/extractor.ex
lib/gettext/po/parser.ex
test/gettext/po/parser_test.exs

See https://github.com/elixir-gettext/gettext/commit/bdd7aff1b9a1088af0131b2c30143621b7f1941d#r35590050.
What do you think about this approach?

Preserve whitespaces in flags

---

lib/gettext/merger.ex
test/gettext/merger_test.exs

Preserve fuzzy Flag when merging entries

---

lib/mix/tasks/gettext.extract.ex
test/mix/tasks/gettext.extract_test.exs

This PR addresses #286.
While still a work in progress (mostly test clean up that I want to do), I figured I would throw up the PR to get eyes on it sooner rather than later in case the approach I took was off.
Thanks in advance for reviewing the PR :)

Added --check-unextracted to extract mix task

---

lib/gettext/po.ex
test/gettext/extractor_test.exs
test/gettext/po_test.exs

Fixes #255 
Update tests to match this new behavior

Put each reference on its own line

---

lib/gettext.ex
lib/gettext/compiler.ex
lib/gettext/interpolation.ex
test/gettext/interpolation_test.exs

This is a preparation to build pluggable interpolation backends in the future.
Follow up from https://github.com/elixir-gettext/gettext/pull/291#issuecomment-955536435

Refactor Interpolation to be more self contained

---

lib/gettext/plural.ex

It is simpler and requires considerably less infrastructure.

Bring back previous gettext plural implementation

---

lib/gettext/merger.ex

Follow up to https://github.com/elixir-gettext/gettext/pull/322. Shout out to accessors 😄

Simplify Gettext.Merger.prune_references/2

---

lib/gettext.ex

I've been meaning to wrap my head around Gettext for a while. When I first looked at it, I was confused about how the English string could be the message id without that being very brittle. Now that I understand better, I wrote this introduction which (among other things) explains that.

Add a 'Basic Overview' docs section

---

lib/gettext/compiler.ex
test/fixtures/single_messages/ja/LC_MESSAGES/errors.po
test/gettext_test.exs
test/test_helper.exs

fixes compiler plural_forms_fun name interpolation

---

lib/gettext/extractor.ex
lib/mix/tasks/gettext.extract.ex
test/gettext/extractor_test.exs
test/mix/tasks/gettext.extract_test.exs

Run merge for `mix gettext.extract` pot files even if they are unchanged

---

lib/gettext.ex

Minor text edit for formatting

edited url to match the module name format
